# Generated by Django 2.2.5 on 2019-09-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190927_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_publick',
            field=models.BooleanField(default=True),
        ),
    ]
